// config/client.ts
// ============================================================================
// CLIENT CONFIGURATION - Single Source of Truth
//
// This file is generated by the Setup Wizard. All other files reference
// these values via clientConfig.
//
// DO NOT hardcode client-specific values elsewhere - always use clientConfig
// ============================================================================

export const clientConfig = {
  // ==========================================================================
  // COMPANY INFORMATION
  // ==========================================================================
  company: {
    name: "COMPANY_NAME",
    legalName: "COMPANY_LEGAL_NAME",
    tagline: "COMPANY_TAGLINE",
    description: "COMPANY_DESCRIPTION",

    // URLs
    website: "https://example.com",
    platformUrl: "https://platform.example.com",

    // Contact
    supportEmail: "support@example.com",
    salesEmail: "sales@example.com",

    // Social
    social: {
      linkedin: "https://linkedin.com/company/example",
      twitter: "https://twitter.com/example",
      youtube: "https://youtube.com/@example",
    },

    // Logo paths (relative to /public)
    logo: {
      light: "/logo-light.svg",
      dark: "/logo-dark.svg",
      favicon: "/favicon.ico",
    },
  },

  // ==========================================================================
  // ADMIN USER (Primary Contact)
  // ==========================================================================
  admin: {
    firstName: "ADMIN_FIRST_NAME",
    lastName: "ADMIN_LAST_NAME",
    email: "admin@example.com",
    phone: "+1234567890",
    position: "Managing Partner",
    linkedIn: "https://linkedin.com/in/admin",
  },

  // ==========================================================================
  // OFFICE LOCATIONS
  // ==========================================================================
  offices: [
    {
      city: "CITY_NAME",
      country: "COUNTRY_NAME",
      address: "STREET_ADDRESS",
      phone: "+1234567890",
      isPrimary: true,
    },
  ],

  // ==========================================================================
  // THEME & BRANDING
  // ==========================================================================
  theme: {
    mode: "dark" as "dark" | "light",
    colors: {
      primary: "#3B82F6",      // Main brand color
      primaryHover: "#2563EB",
      accent: "#10B981",       // Secondary/accent color
      accentHover: "#059669",
      background: "#0F172A",   // Dark mode background
      surface: "#1E293B",      // Card/surface background
      text: "#F8FAFC",
      textMuted: "#94A3B8",
      border: "#334155",
      gradient: { from: "#3B82F6", via: "#0F172A", to: "#10B981" },
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
    },
    gradients: {
      hero: "from-blue-600 to-purple-600",
      button: "from-blue-500 to-blue-600",
      card: "from-slate-800 to-slate-900",
    },
    fonts: {
      heading: "Inter",
      body: "Inter",
    },
    borderRadius: "0.5rem",
  },

  // ==========================================================================
  // LANDING PAGE CONTENT
  // ==========================================================================
  landing: {
    hero: {
      headline: "HERO_HEADLINE",
      subHeadline: "HERO_SUBHEADLINE",
      ctaText: "Get Started",
      ctaLink: "/signup/founder",
      secondaryCtaText: "Learn More",
      secondaryCtaLink: "#how-it-works",
    },
    stats: [
      { value: "500+", label: "Founders Coached" },
      { value: "$2B+", label: "Capital Raised" },
      { value: "85%", label: "Success Rate" },
      { value: "50+", label: "Countries" },
    ],
    valueProps: [
      {
        icon: "Brain",
        title: "AI-Powered Coaching",
        description: "Get personalized feedback on your pitch deck and presentation skills.",
      },
      {
        icon: "Target",
        title: "Investor Matching",
        description: "Connect with investors who match your stage, sector, and geography.",
      },
      {
        icon: "TrendingUp",
        title: "Track Progress",
        description: "Monitor your readiness score and improvement over time.",
      },
    ],
    howItWorks: [
      {
        step: 1,
        title: "Upload Your Deck",
        description: "Submit your pitch deck for AI analysis.",
      },
      {
        step: 2,
        title: "Get Coached",
        description: "Receive personalized feedback and practice with AI.",
      },
      {
        step: 3,
        title: "Meet Investors",
        description: "Get matched with relevant investors when ready.",
      },
    ],
  },

  // ==========================================================================
  // INVESTMENT THESIS (Seeded from website, refined by admin)
  // ==========================================================================
  thesis: {
    focusAreas: [
      "Compelling founder story",
      "Clear problem-solution fit",
      "Scalable business model",
    ],
    sectors: [
      "Technology",
      "Healthcare",
      "Fintech",
      "Consumer",
    ],
    stages: [
      "Pre-Seed",
      "Seed",
      "Series A",
    ],
    geographies: [
      "Global",
    ],
    ticketSize: {
      min: "$100K",
      max: "$5M",
      sweet: "$500K - $2M",
    },
    philosophy: "INVESTMENT_PHILOSOPHY",
    idealFounder: "IDEAL_FOUNDER_DESCRIPTION",
    dealBreakers: [
      "No clear differentiation",
      "Unrealistic valuations",
      "Weak founding team",
    ],
  },

  // ==========================================================================
  // AI COACHING CONFIGURATION
  // ==========================================================================
  coaching: {
    coachName: "COACH_NAME",
    coachPersonality: "COACH_PERSONALITY_DESCRIPTION",
    voiceAgentId: "", // ElevenLabs agent ID (set after creation)

    scoringFocus: "storytelling" as "storytelling" | "impact" | "growth",

    scoringCriteria: [
      { key: "narrative", label: "Narrative Clarity", weight: 0.20 },
      { key: "problem", label: "Problem Definition", weight: 0.15 },
      { key: "solution", label: "Solution Fit", weight: 0.15 },
      { key: "market", label: "Market Opportunity", weight: 0.15 },
      { key: "traction", label: "Traction & Proof", weight: 0.15 },
      { key: "team", label: "Team Credibility", weight: 0.10 },
      { key: "financials", label: "Financial Viability", weight: 0.10 },
    ],

    // Welcome messages for different coaching modes
    welcomeMessages: {
      discovery: `Welcome to {company} Story Discovery! I'm {coach}, and I'll help you uncover the compelling narrative behind your startup.`,
      practice: `Ready to practice your pitch? I'm {coach}, and I'll give you real-time feedback to sharpen your delivery.`,
      simulation: `Let's simulate an investor meeting. I'll play the role of different investor types to prepare you for the real thing.`,
    },
  },

  // ==========================================================================
  // PLATFORM SETTINGS
  // ==========================================================================
  platform: {
    // URL prefix for portal routes (middleware rewrites to /portal/)
    urlPrefix: "portal",

    // Admin role name in database
    adminRole: "portal_admin",

    // Feature toggles
    features: {
      voiceCoaching: true,
      investorMatching: true,
      deckVersioning: true,
      teamMembers: false,
      analytics: true,
      apiAccess: false,
    },

    // Founder journey steps
    founderJourney: [
      { id: "upload", label: "Upload Deck", icon: "Upload" },
      { id: "profile", label: "Complete Profile", icon: "User" },
      { id: "discovery", label: "Story Discovery", icon: "MessageSquare" },
      { id: "refine", label: "Refine Materials", icon: "FileEdit" },
      { id: "practice", label: "Practice Pitch", icon: "Mic" },
    ],

    // Readiness levels
    readinessLevels: [
      { key: "not-ready", label: "Not Ready", minScore: 0, color: "red" },
      { key: "needs-work", label: "Needs Work", minScore: 40, color: "orange" },
      { key: "almost-ready", label: "Almost Ready", minScore: 60, color: "yellow" },
      { key: "investor-ready", label: "Investor Ready", minScore: 80, color: "green" },
    ],

    // Auto-reply template for founder submissions
    autoReplyTemplate: `
Thank you for submitting your pitch to {company}!

We've received your deck and our AI coaching system is analyzing it now. 
You'll receive your initial feedback within 24 hours.

In the meantime, you can:
- Complete your founder profile
- Start your Story Discovery session
- Practice your pitch with our AI coach

Best regards,
The {company} Team
    `,
  },

  // ==========================================================================
  // FOOTER CONTENT
  // ==========================================================================
  footer: {
    description: "FOOTER_DESCRIPTION",
    serviceLinks: [
      { label: "For Founders", href: "/signup/founder" },
      { label: "For Investors", href: "/login" },
      { label: "Pricing", href: "/pricing" },
    ],
    companyLinks: [
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
      { label: "Careers", href: "/careers" },
    ],
    legalLinks: [
      { label: "Privacy Policy", href: "/privacy" },
      { label: "Terms of Service", href: "/terms" },
    ],
    copyright: `© {year} {company}. All rights reserved.`,
  },

  // ==========================================================================
  // LEGAL & COMPLIANCE
  // ==========================================================================
  legal: {
    privacyUrl: "/privacy",
    termsUrl: "/terms",
    copyrightYear: new Date().getFullYear(),
    complianceRegions: ["GDPR", "CCPA"],
  },

  // ==========================================================================
  // EXTERNAL SERVICE IDS (Populated during setup)
  // ==========================================================================
  services: {
    supabase: {
      projectId: "",
      url: "",
      // Keys stored in env vars, not here
    },
    vercel: {
      projectId: "",
      deploymentUrl: "",
    },
    elevenlabs: {
      agentId: "",
      voiceId: "",
    },
    anthropic: {
      // Key stored in env vars
    },
  },
};

// ==========================================================================
// HELPER FUNCTIONS
// ==========================================================================

/** Get company name */
export const getCompanyName = () => clientConfig.company.name;

/** Get admin full name */
export const getAdminName = () =>
  `${clientConfig.admin.firstName} ${clientConfig.admin.lastName}`;

/** Get admin role */
export const getAdminRole = () => clientConfig.platform.adminRole;

/** Get URL prefix */
export const getUrlPrefix = () => clientConfig.platform.urlPrefix;

/** Get coach name */
export const getCoachName = () => clientConfig.coaching.coachName;

/** Get portal route */
export const getPortalRoute = (path: string) =>
  `/${clientConfig.platform.urlPrefix}${path}`;

/** Get themed color */
export const getThemeColor = (color: keyof typeof clientConfig.theme.colors) =>
  clientConfig.theme.colors[color];

/** Replace template variables in text */
export const replaceTemplateVars = (text: string): string => {
  return text
    .replace(/{company}/g, clientConfig.company.name)
    .replace(/{coach}/g, clientConfig.coaching.coachName)
    .replace(/{year}/g, String(clientConfig.legal.copyrightYear))
    .replace(/{admin}/g, getAdminName())
    .replace(/{email}/g, clientConfig.company.supportEmail);
};

/** Check if feature is enabled */
export const isFeatureEnabled = (feature: keyof typeof clientConfig.platform.features) =>
  clientConfig.platform.features[feature];

// Type export for use in other files
export type ClientConfig = typeof clientConfig;